[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/about-us"
  to = "/about-us/"
  status = 301

[[redirects]]
  from = "/programs"
  to = "/programs/"
  status = 301

[[redirects]]
  from = "/support-us"
  to = "/support-us/"
  status = 301

[[redirects]]
  from = "/contact-us"
  to = "/contact-us/"
  status = 301
